name: HTTP Request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send-request:
    runs-on: ubuntu-latest

    steps:
    - name: Send request
      run: |
        curl --retry-connrefused --keepalive-time 300 https://NTEST.euyix.repl.co
